GET http://localhost:5000/ads

###

POST http://localhost:5000/ads/search
Content-Type: application/json

{
    "searchInput":"MADE WITH LOVE FOR YOUR LOVE FOR CRICKET"
}
###

POST http://localhost:5000/ads
Content-Type: application/json

{
    "companyId":"6363a239dabe83469a9bcaae",
    "primaryText":"Timeless trainers with rugged style, made in part with recycled materials.",
    "headline":"Stan Smith Shoes",
    "description":"Swerve through crowds and cruise across sidewalks. These adidas Stan Smith shoes are built for city exploration. A style that's been effortlessly cool for 50 years and counting, they've been updated with a durable CORDURA upper that holds up to the scuffs and scrapes of daily life. Just like the original, their simple aesthetic pairs well with every single thing on your calendar.",
    "cta":"Buy Now",
    "imageUrl":"https://drive.google.com/file/d/17kQiqGnkLEZZmnzLlWG7ZIlN6XbwAVfb/view?usp=sharing"
}

###
GET http://localhost:5000/ads/636235bf83e1e21dc74d3532

### COMPANIES ###

GET http://localhost:5000/companies
###

GET http://localhost:5000/companies/6363a1cadabe83469a9bcaa8

###
POST http://localhost:5000/companies
Content-Type: application/json

{
    "name":"Purple",
    "url":"http://purple.com/"
}